#pragma once
#include "status.h"
#include <windows.h>


/*		CONSTANTS		*/
#define MIN_NUM_OF_ARGUMENTS 3
#define PID 2
#define DLL_TO_RUN 1
#define INITIAL_PID 0
#define INVALID_PROCESS_HANDLE NULL
#define INVALID_MEMMORY_SIZE_TO_RESERVE 0
#define MAXIMUM_PATH_SIZE 260
#define INVALID_BASE_MEMMORY_ADDRESS NULL
#define MEMMORY_WRITING_FAILED 0
#define INVALID_MODULE_HANDLE NULL
#define INVALID_FUNCTION_ADDRESS NULL
#define INVALID_THREAD_HANDLE NULL



