#pragma once

/*		CONSTANTS		*/
typedef enum {
    STATUS_ERROR = -1,
    STATUS_SUCCESS = 0,
    INVALID_NUMBER_OF_ARGUMENTS,
    INVALID_PID,
    INVALID_DLL_PATH_SIZE,
    FAILED_TO_GET_PROCESS_HANDLE,
    FAILED_TO_ALLOCATE_REMOTE_MEMMORY,
    FAILED_TO_WRITE_MEMMORY,
    FAILED_TO_GET_MODULE_HANDLE,
    FAILED_TO_GET_FUNCTION_ADDRESS,
    FAILED_TO_CREATE_REMOTE_THREAD
}StatusCode;